/**
 * AIR Transpiler
 *
 * Converts a validated AirAST into a working React application.
 * Output is a complete Vite + React + Tailwind project.
 *
 * This is the core value: .air → working app.
 */

import type { AirAST } from '../parser/types.js';

export interface TranspileOptions {
  /** Output framework (default: react) */
  framework?: 'react';
  /** Output directory */
  outDir?: string;
  /** Include styling (default: true) */
  includeStyles?: boolean;
  /** Pretty print output (default: true) */
  prettyPrint?: boolean;
}

export interface TranspileResult {
  files: OutputFile[];
  stats: {
    inputLines: number;
    outputLines: number;
    compressionRatio: number;
    components: number;
  };
}

export interface OutputFile {
  path: string;
  content: string;
}

export function transpile(
  ast: AirAST,
  options: TranspileOptions = {}
): TranspileResult {
  const opts = {
    framework: 'react' as const,
    includeStyles: true,
    prettyPrint: true,
    ...options,
  };

  const files: OutputFile[] = [];

  // Generate package.json
  files.push({
    path: 'package.json',
    content: generatePackageJson(ast.app.name),
  });

  // Generate main App component
  files.push({
    path: 'src/App.jsx',
    content: generateAppComponent(ast),
  });

  // Generate index.html
  files.push({
    path: 'index.html',
    content: generateIndexHtml(ast.app.name),
  });

  // Generate entry point
  files.push({
    path: 'src/main.jsx',
    content: generateEntryPoint(),
  });

  const outputLines = files.reduce((sum, f) => sum + f.content.split('\n').length, 0);

  return {
    files,
    stats: {
      inputLines: 0, // TODO: track from source
      outputLines,
      compressionRatio: 0, // TODO: calculate
      components: 1, // TODO: count from AST
    },
  };
}

// ---- Generators ----

function generatePackageJson(appName: string): string {
  return JSON.stringify({
    name: appName,
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.2.0',
      vite: '^5.2.0',
    },
  }, null, 2);
}

function generateAppComponent(ast: AirAST): string {
  // TODO: Phase 1 — generate full component from AST
  // This will walk the AST and emit JSX for each UI node

  return `import { useState, useEffect } from 'react';

// Generated by AirEngine from ${ast.app.name}.air
export default function App() {
  // TODO: Generate from @state block
  // TODO: Generate from @ui block

  return (
    <div className="app">
      <h1>${ast.app.name}</h1>
      <p>Generated by AirEngine</p>
    </div>
  );
}
`;
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
`;
}

function generateEntryPoint(): string {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}
