import { useState, useEffect } from 'react';

// Generated by AirEngine from todo.air
export default function App() {
  const [items, setItems] = useState([]);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    try {
      const raw = localStorage.getItem('todo-items');
      if (raw) { const _saved_items = JSON.parse(raw); setItems(_saved_items); }
    } catch (e) { /* ignore corrupt storage */ }
  }, []);

  useEffect(() => {
    localStorage.setItem('todo-items', JSON.stringify(items));
  }, [items]);

  const add = (data) => {
    setItems(prev => [...prev, { ...data, id: Date.now() }]);
  };

  const del = (id) => {
    setItems(prev => prev.filter(item => item.id !== id));
  };


  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
      <header className="flex items-center justify-between p-4 border-b border-[var(--border)]">
        {"Todo App"}
        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{items.length}</span>
      </header>
      <input type="text" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" placeholder="Add..." onKeyDown={(e) => { if (e.key === 'Enter' && e.target.value) { add({text:e.target.value,done:false}); e.target.value = ''; } }} />
      <ul className="space-y-2">
        {items.filter(_item => filter === 'all' || _item.category === filter || _item.done === (filter === 'done')).map((item) => (
          <div key={item.id} className="flex gap-2 items-center">
          <input type="checkbox" checked={item.done} onChange={() => setItems(prev => prev.map(_i => _i.id === item.id ? { ..._i, done: !_i.done } : _i))} />
          <span>{item.text}</span>
          <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors" onClick={() => del(item.id)}>✕</button>
          </div>
        ))}
      </ul>
      <div className="flex gap-2">
        {["all", "active", "done"].map((_tab) => (
          <button key={_tab} className={`px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors ${filter === _tab ? 'bg-[var(--accent)] text-white' : 'bg-transparent hover:bg-[var(--hover)]'}`} onClick={() => setFilter(_tab)}>{_tab}</button>
        ))}
      </div>
      <footer className="p-4 text-center text-sm text-[var(--muted)]">{`${items.filter(i => !i.done).length} items left`}</footer>
    </div>
  );
}
