// Generated by AirEngine v0.1.7 from todo.air
import { useState, useEffect } from 'react';

// Generated by AirEngine from todo.air
export default function App() {
  const [items, setItems] = useState([]);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    try {
      const raw = localStorage.getItem('todo-items');
      if (raw) { const _saved_items = JSON.parse(raw); setItems(_saved_items); }
    } catch (e) { /* ignore corrupt storage */ }
  }, []);

  useEffect(() => {
    localStorage.setItem('todo-items', JSON.stringify(items));
  }, [items]);

  const add = (data) => {
    setItems(prev => [...prev, { ...data, id: Date.now() }]);
  };

  const del = (id) => {
    setItems(prev => prev.filter(item => item.id !== id));
  };


  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
      <div className="max-w-[900px] mx-auto px-4 sm:px-6 py-8 space-y-6">
        <header className="flex flex-col sm:flex-row items-center justify-between gap-4 py-4 mb-2 border-b border-[var(--border)]">
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-bold">Todo App</h1>
            <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{items.length}</span>
          </div>
        </header>
        <div className="flex gap-2">
          <input type="text" className="rounded-[var(--radius)] px-3.5 py-2.5 flex-1" placeholder="Add..." onKeyDown={(e) => { if (e.key === 'Enter' && e.target.value) { add({text:e.target.value,done:false}); e.target.value = ''; } }} />
          <button className="bg-[var(--accent)] text-white px-4 py-2.5 rounded-[var(--radius)] cursor-pointer hover:opacity-90 transition-colors" onClick={(e) => { const _inp = e.currentTarget.previousElementSibling; if (_inp?.value) { add({text:_inp.value,done:false}); _inp.value = ''; } }}>Add</button>
        </div>
        <ul className="space-y-3">
          {items.filter(_item => filter === 'all' || _item.status === filter).length === 0 ? (
            <div className="empty-state">No items yet</div>
          ) : items.filter(_item => filter === 'all' || _item.status === filter).map((item) => (
            <div key={item.id} className="flex gap-3 items-center bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] px-4 py-3">
            <input type="checkbox" checked={item.done} onChange={() => setItems(prev => prev.map(_i => _i.id === item.id ? { ..._i, done: !_i.done } : _i))} />
            <span className="flex-1">{item.text}</span>
            <button className="p-2 rounded-full hover:bg-[var(--hover)] cursor-pointer transition-colors" onClick={() => del(item.id)}>✕</button>
            </div>
          ))}
        </ul>
        <div className="flex gap-1 p-1 bg-[var(--surface)] rounded-[var(--radius)]">
          {["all", "active", "done"].map((_tab) => (
            <button key={_tab} className={`px-4 py-2 rounded-[calc(var(--radius)-4px)] cursor-pointer transition-colors ${filter === _tab ? 'bg-[var(--accent)] text-white' : 'bg-transparent text-[var(--muted)] hover:text-[var(--fg)]'}`} onClick={() => setFilter(_tab)}>{_tab.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}</button>
          ))}
        </div>
        <footer className="mt-auto p-4 text-center text-sm text-[var(--muted)]">{`${items.filter(i => !i.done).length} items left`}</footer>
      </div>
    </div>
  );
}
