#!/usr/bin/env npx tsx
/**
 * Self-Heal Incident Classifier (SH1)
 *
 * Deterministic pattern-matching classifier for incident triage.
 * No LLM calls — pure pattern registry matching.
 *
 * Usage:  node --import tsx scripts/classify-incident.ts <incident-path>
 * Output: Updates incident.json in-place with triage data
 * Exit:   0 = classified, 1 = error
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { validateJsonSchema } from '../tests/schema-validator.js';

// ---- Types ----

export interface TriageResult {
  classification: string;
  suspected_subsystem: string;
  confidence: 'high' | 'medium' | 'low';
  triage_notes: string;
  recommended_next_step: string;
  suggested_tests: string[];
  suggested_invariant: string | null;
}

export interface PatternEntry {
  id: string;
  subsystem: string;
  confidence: 'high' | 'medium' | 'low';
  match: (incident: Record<string, unknown>) => boolean;
  notes: string;
  next_step: string;
  suggested_tests: string[];
  suggested_invariant: string | null;
}

// ---- Helpers ----

function getErrorMessage(incident: Record<string, unknown>): string {
  const err = incident.error as Record<string, unknown> | undefined;
  return String(err?.message || incident.summary || '').toLowerCase();
}

function getRawOutput(incident: Record<string, unknown>): string {
  const err = incident.error as Record<string, unknown> | undefined;
  return String(err?.raw_output || '').toLowerCase();
}

function getStage(incident: Record<string, unknown>): string {
  return String(incident.stage || '');
}

function getSummary(incident: Record<string, unknown>): string {
  return String(incident.summary || '').toLowerCase();
}

function getPageName(incident: Record<string, unknown>): string {
  const inputs = incident.inputs as Record<string, unknown> | undefined;
  return String(inputs?.page_name || '').toLowerCase();
}

function getRoutePath(incident: Record<string, unknown>): string {
  const inputs = incident.inputs as Record<string, unknown> | undefined;
  return String(inputs?.route_path || '').toLowerCase();
}

function hasTag(incident: Record<string, unknown>, tag: string): boolean {
  const tags = incident.tags as string[] | undefined;
  return tags?.some(t => t.toLowerCase() === tag.toLowerCase()) ?? false;
}

function hasEvidence(incident: Record<string, unknown>, kind: string): boolean {
  const evidence = incident.evidence as Array<Record<string, unknown>> | undefined;
  return evidence?.some(e => e.kind === kind) ?? false;
}

// ---- Pattern Registry (centralized, ordered by priority) ----

export const PATTERN_REGISTRY: PatternEntry[] = [
  // --- Frontend Runtime / Codegen ---
  {
    id: 'codegen-paginated-shape-mismatch',
    subsystem: 'page-gen',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const raw = getRawOutput(inc);
      return (msg.includes('.map is not a function') || raw.includes('.map is not a function'))
        && !msg.includes('backend');
    },
    notes: 'Generated page assigns paginated response object directly to array state without unwrapping .data. The api.getX() call returns { data: [], meta: {} } but state expects a plain array.',
    next_step: 'Check page-gen.ts data fetch unwrapping — ensure `res.data ?? res` pattern is applied.',
    suggested_tests: ['invariant: paginated-list-unwrapping', 'test: dashboard data shape handling'],
    suggested_invariant: 'paginated-list-unwrapping',
  },
  {
    id: 'codegen-state-ordering-or-missing-binding',
    subsystem: 'page-gen',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      return msg.includes('is not defined') && !msg.includes('route') && !msg.includes('env');
    },
    notes: 'Generated component references a variable that was never declared. Usually a state var that should have been generated by detectUndeclaredStateVars or binding.dataSources.',
    next_step: 'Check page-gen.ts state variable detection and generation order.',
    suggested_tests: ['test: state variable completeness for page type'],
    suggested_invariant: null,
  },
  {
    id: 'codegen-duplicate-declaration',
    subsystem: 'page-gen',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      return msg.includes('has already been declared') || msg.includes('identifier') && msg.includes('already');
    },
    notes: 'Generated component declares the same variable twice. Often caused by both binding.dataSources and detectUndeclaredStateVars emitting the same state declaration.',
    next_step: 'Check page-gen.ts declaredVars tracking and public/auth route filtering in detectPageResource.',
    suggested_tests: ['test: no duplicate state declarations in dashboard', 'invariant: unique-state-declarations'],
    suggested_invariant: null,
  },
  {
    id: 'codegen-unwired-action-handler',
    subsystem: 'page-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return msg.includes('is not a function') && !msg.includes('.map')
        || summary.includes('dead button')
        || summary.includes('unwired')
        || summary.includes('no-op handler');
    },
    notes: 'Button onClick references a handler function that was never generated. mutation-gen or page-gen did not wire the action.',
    next_step: 'Check mutation-gen.ts for handler pattern matching and page-gen.ts for mutation wiring.',
    suggested_tests: ['test: action handlers are defined for all onClick references'],
    suggested_invariant: null,
  },
  {
    id: 'codegen-dead-cta-button',
    subsystem: 'jsx-gen',
    confidence: 'high',
    match: (inc) => {
      const summary = getSummary(inc);
      const stage = getStage(inc);
      return (stage === 'runtime-ui' || stage === 'qa-visual')
        && (hasTag(inc, 'public-cta') || hasTag(inc, 'navigation'))
        && (summary.includes('cta') || summary.includes('button') || summary.includes('dead') || summary.includes('respond'));
    },
    notes: 'Public CTA button rendered without onClick handler. Buttons like "View Portfolio" or "Book a Session" need navigation wiring via setCurrentPage.',
    next_step: 'Check jsx-gen.ts generateFlowJSX → element>text path for CTA button matching via matchCtaToPage.',
    suggested_tests: ['test: photography CTA buttons have onClick handlers', 'golden: G11 public CTA wiring'],
    suggested_invariant: null,
  },
  {
    id: 'codegen-route-navigation-bug',
    subsystem: 'jsx-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return summary.includes('navigation') && (summary.includes('wrong page') || summary.includes('redirect'))
        || msg.includes('setcurrentpage') && msg.includes('wrong');
    },
    notes: 'setCurrentPage targets wrong page name, or default page is incorrect.',
    next_step: 'Check jsx-gen.ts page routing and default currentPage assignment.',
    suggested_tests: ['test: default currentPage is correct for app type'],
    suggested_invariant: null,
  },
  {
    id: 'codegen-loading-deadlock',
    subsystem: 'page-gen',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('loading') && (summary.includes('never') || summary.includes('stuck') || summary.includes('deadlock') || summary.includes('spinner'));
    },
    notes: 'Loading state never transitions to loaded. Usually a missing .finally(() => setLoading(false)) or Promise rejection not handled.',
    next_step: 'Check page-gen.ts loading state transitions in useEffect.',
    suggested_tests: ['test: loading state always resolves'],
    suggested_invariant: null,
  },

  // --- Visual / Layout / CSS ---
  {
    id: 'layout-auth-wrapper-composition',
    subsystem: 'jsx-gen',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      const stage = getStage(inc);
      return (stage === 'qa-visual' || stage === 'runtime-ui')
        && (summary.includes('auth') || summary.includes('login') || summary.includes('wrapper'))
        && (summary.includes('width') || summary.includes('layout') || summary.includes('nested') || summary.includes('composition'));
    },
    notes: 'Auth page wrapped in conflicting layout shells. Login page has nested constrained wrappers breaking the visual layout.',
    next_step: 'Check jsx-gen.ts auth page rendering path — ensure auth pages are not wrapped in Layout.',
    suggested_tests: ['test: auth pages render without Layout wrapper', 'invariant: auth-wrapper-composition'],
    suggested_invariant: 'auth-wrapper-composition',
  },
  {
    id: 'style-global-cta-width-regression',
    subsystem: 'scaffold',
    confidence: 'high',
    match: (inc) => {
      const summary = getSummary(inc);
      const stage = getStage(inc);
      return (stage === 'qa-visual' || stage === 'runtime-ui')
        && summary.includes('width') && (summary.includes('button') || summary.includes('submit') || summary.includes('cta'))
        && (summary.includes('global') || summary.includes('all') || summary.includes('full'));
    },
    notes: 'Global CSS rule forces all form submit buttons to full width, breaking non-auth button layouts.',
    next_step: 'Check scaffold.ts generated CSS for overly broad button/submit width rules.',
    suggested_tests: ['invariant: global-auth-submit-width'],
    suggested_invariant: 'global-auth-submit-width',
  },
  {
    id: 'style-responsive-overflow',
    subsystem: 'scaffold',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      const stage = getStage(inc);
      return (stage === 'qa-visual' || stage === 'runtime-ui')
        && (summary.includes('overflow') || summary.includes('responsive') || summary.includes('mobile'))
        && (summary.includes('break') || summary.includes('wrap') || summary.includes('scroll'));
    },
    notes: 'Content overflows container on smaller viewports.',
    next_step: 'Check scaffold.ts responsive breakpoints and page-gen.ts grid/flex layouts.',
    suggested_tests: ['test: grid layouts have responsive column counts'],
    suggested_invariant: null,
  },
  {
    id: 'style-contrast-unreadable',
    subsystem: 'scaffold',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return (summary.includes('contrast') || summary.includes('unreadable') || summary.includes('invisible'))
        && (summary.includes('text') || summary.includes('color'));
    },
    notes: 'Text color has insufficient contrast against background.',
    next_step: 'Check scaffold.ts CSS variable definitions for theme contrast ratios.',
    suggested_tests: ['test: text colors have sufficient contrast ratio'],
    suggested_invariant: null,
  },
  {
    id: 'style-card-form-malformed',
    subsystem: 'page-gen',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      const stage = getStage(inc);
      return (stage === 'qa-visual' || stage === 'runtime-ui')
        && (summary.includes('card') || summary.includes('form') || summary.includes('table'))
        && (summary.includes('broken') || summary.includes('malformed') || summary.includes('missing'));
    },
    notes: 'Card, form, or table component has structural layout issues.',
    next_step: 'Check page-gen.ts component generation for the affected element type.',
    suggested_tests: ['test: generated cards/forms have valid structure'],
    suggested_invariant: null,
  },

  // --- Backend / API / Runtime ---
  {
    id: 'backend-route-guard-misclassification',
    subsystem: 'server-entry-gen',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      const route = getRoutePath(inc);
      return (summary.includes('public') && (summary.includes('auth') || summary.includes('401') || summary.includes('protected')))
        || (msg.includes('401') && route.includes('/public/'))
        || (summary.includes('route') && summary.includes('guard') && summary.includes('wrong'));
    },
    notes: 'Public route unexpectedly requires authentication. The /public/ path exemption is missing from auth middleware or route-level guard.',
    next_step: 'Check server-entry-gen.ts auth middleware exemption list and api-router-gen.ts requireAuth attachment.',
    suggested_tests: ['invariant: public-route-auth-exemption', 'test: /public/ routes accessible without token'],
    suggested_invariant: 'public-route-auth-exemption',
  },
  {
    id: 'backend-route-registration-gap',
    subsystem: 'api-router-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return (msg.includes('404') || msg.includes('not found'))
        && (summary.includes('route') || summary.includes('endpoint') || summary.includes('api'));
    },
    notes: 'Declared API route not registered in generated server. Route handler missing from api-router-gen output.',
    next_step: 'Check api-router-gen.ts route generation loop and expandedRoutes coverage.',
    suggested_tests: ['test: all declared API routes are registered'],
    suggested_invariant: null,
  },
  {
    id: 'backend-query-param-handling',
    subsystem: 'api-router-gen',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return (summary.includes('filter') || summary.includes('sort') || summary.includes('search') || summary.includes('query param'))
        && (summary.includes('ignored') || summary.includes('not working') || summary.includes('wrong'));
    },
    notes: 'Query parameters for filtering/sorting/searching not handled by generated route handler.',
    next_step: 'Check api-router-gen.ts query parameter extraction and Prisma where clause building.',
    suggested_tests: ['test: filter/sort/search params produce correct queries'],
    suggested_invariant: null,
  },
  {
    id: 'backend-aggregate-shape-mismatch',
    subsystem: 'api-router-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return (summary.includes('stats') || summary.includes('aggregate') || summary.includes('count'))
        && (summary.includes('shape') || summary.includes('mismatch') || summary.includes('undefined') || msg.includes('undefined'));
    },
    notes: 'Stats/aggregate endpoint returns unexpected shape. Dashboard expects specific metric keys.',
    next_step: 'Check api-router-gen.ts stats endpoint generation and dashboard page metric references.',
    suggested_tests: ['test: stats endpoint returns expected metric keys'],
    suggested_invariant: null,
  },
  {
    id: 'backend-middleware-wiring',
    subsystem: 'server-entry-gen',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('middleware') && (summary.includes('missing') || summary.includes('order') || summary.includes('not applied'));
    },
    notes: 'Middleware missing or applied in wrong order in generated server.',
    next_step: 'Check server-entry-gen.ts middleware registration order.',
    suggested_tests: ['test: middleware applied in correct order'],
    suggested_invariant: null,
  },

  // --- DB / Schema / Seed / Data ---
  {
    id: 'data-missing-field-or-index',
    subsystem: 'prisma-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return (msg.includes('unknown field') || msg.includes('column') || msg.includes('not found in schema'))
        || (summary.includes('missing') && (summary.includes('field') || summary.includes('index') || summary.includes('column')));
    },
    notes: 'Generated Prisma schema missing a field or index referenced by generated code.',
    next_step: 'Check prisma.ts model field generation and .air @db block definition.',
    suggested_tests: ['test: all referenced fields exist in Prisma schema'],
    suggested_invariant: null,
  },
  {
    id: 'data-seed-determinism-failure',
    subsystem: 'seed-gen',
    confidence: 'high',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('seed') && (summary.includes('determinism') || summary.includes('different output') || summary.includes('non-deterministic'));
    },
    notes: 'Seed script produces different output across runs.',
    next_step: 'Check seed-gen.ts for non-deterministic operations (random, Date.now, etc.).',
    suggested_tests: ['test: seed output is deterministic across runs'],
    suggested_invariant: null,
  },
  {
    id: 'data-seed-shape-mismatch',
    subsystem: 'seed-gen',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('seed') && (summary.includes('shape') || summary.includes('mismatch') || summary.includes('generic') || summary.includes('cover_color'));
    },
    notes: 'Seed data does not match UI display expectations. Generic placeholder values used instead of domain-appropriate data.',
    next_step: 'Check seed-gen.ts data generation heuristics for domain-specific fields.',
    suggested_tests: ['test: seed data has appropriate values for display fields'],
    suggested_invariant: null,
  },
  {
    id: 'data-null-handling',
    subsystem: 'page-gen',
    confidence: 'medium',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      return (msg.includes('cannot read properties of null') || msg.includes('cannot read properties of undefined'))
        && !msg.includes('.map');
    },
    notes: 'Generated page does not handle null/undefined values from optional fields.',
    next_step: 'Check page-gen.ts optional field rendering — ensure `?? "--"` or similar fallback.',
    suggested_tests: ['test: optional fields render gracefully when null'],
    suggested_invariant: null,
  },

  // --- Transpiler / Compiler ---
  {
    id: 'transpiler-codegen-regression',
    subsystem: 'transpiler',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('regression') && (summary.includes('codegen') || summary.includes('transpile') || summary.includes('generated'));
    },
    notes: 'Previously working codegen pattern broken by recent change.',
    next_step: 'Compare golden snapshot hashes to identify changed files.',
    suggested_tests: ['test: snapshot hashes stable after change'],
    suggested_invariant: null,
  },
  {
    id: 'transpiler-snapshot-drift',
    subsystem: 'transpiler',
    confidence: 'high',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('snapshot') && (summary.includes('drift') || summary.includes('mismatch') || summary.includes('changed'));
    },
    notes: 'Golden output snapshot hashes changed unexpectedly.',
    next_step: 'Run SNAPSHOT_UPDATE=1 npx vitest run tests/snapshots.test.ts and review diffs.',
    suggested_tests: ['test: all snapshot hashes match golden baseline'],
    suggested_invariant: null,
  },

  // --- Docs / Config / Operator ---
  {
    id: 'runtime-missing-provider-env',
    subsystem: 'operator-config',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return (msg.includes('env') || msg.includes('environment'))
        && (msg.includes('missing') || msg.includes('undefined') || msg.includes('not set'))
        || (summary.includes('env') && summary.includes('missing'));
    },
    notes: 'Required environment variable not set. Server or client fails to start.',
    next_step: 'Check .env template generation in scaffold.ts and docs for env var requirements.',
    suggested_tests: ['test: all required env vars documented and templated'],
    suggested_invariant: null,
  },
  {
    id: 'config-port-mismatch',
    subsystem: 'operator-config',
    confidence: 'high',
    match: (inc) => {
      const msg = getErrorMessage(inc);
      const summary = getSummary(inc);
      return (summary.includes('port') || msg.includes('port'))
        && (summary.includes('mismatch') || summary.includes('cors') || msg.includes('eaddrinuse') || msg.includes('connection refused'));
    },
    notes: 'Server and client port configuration mismatch, or port already in use.',
    next_step: 'Check scaffold.ts env var generation for port/CORS consistency.',
    suggested_tests: ['test: client VITE_API_BASE_URL matches server PORT'],
    suggested_invariant: null,
  },
  {
    id: 'docs-stale-command',
    subsystem: 'docs',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('docs') && (summary.includes('stale') || summary.includes('wrong') || summary.includes('outdated'))
        && (summary.includes('command') || summary.includes('script') || summary.includes('count'));
    },
    notes: 'Documentation references outdated commands, test counts, or script names.',
    next_step: 'Update docs to match current codebase state.',
    suggested_tests: ['test: documented commands exist in package.json'],
    suggested_invariant: null,
  },

  // --- .air Input ---
  {
    id: 'air-input-parse',
    subsystem: 'parser',
    confidence: 'high',
    match: (inc) => {
      const stage = getStage(inc);
      const msg = getErrorMessage(inc);
      return stage === 'validate' && (msg.includes('parse') || msg.includes('syntax') || msg.includes('unexpected token'));
    },
    notes: '.air file has syntax errors that prevent parsing.',
    next_step: 'Run `air validate <file>` and fix syntax errors.',
    suggested_tests: ['test: .air file parses without errors'],
    suggested_invariant: null,
  },
  {
    id: 'air-input-validation',
    subsystem: 'validator',
    confidence: 'high',
    match: (inc) => {
      const stage = getStage(inc);
      const msg = getErrorMessage(inc);
      return stage === 'validate' && (msg.includes('validation') || msg.includes('air-e') || msg.includes('air-w'));
    },
    notes: '.air file parses but fails semantic validation.',
    next_step: 'Run `air validate <file>` and address validation errors.',
    suggested_tests: ['test: .air file passes validation'],
    suggested_invariant: null,
  },

  // --- Performance ---
  {
    id: 'perf-transpile-slowdown',
    subsystem: 'transpiler',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return (summary.includes('slow') || summary.includes('performance') || summary.includes('latency'))
        && (summary.includes('transpile') || summary.includes('compile'));
    },
    notes: 'Transpile time exceeds performance budget.',
    next_step: 'Run bench.test.ts and check timing stats in TranspileResult.',
    suggested_tests: ['test: transpile time under 200ms budget'],
    suggested_invariant: null,
  },
  {
    id: 'perf-stability-regression',
    subsystem: 'transpiler',
    confidence: 'medium',
    match: (inc) => {
      const summary = getSummary(inc);
      return summary.includes('stability') && summary.includes('regression');
    },
    notes: 'Stability sweep case regressed.',
    next_step: 'Run stability-sweep and compare with previous results.',
    suggested_tests: ['test: stability sweep all cases pass'],
    suggested_invariant: null,
  },

  // --- Runtime QA (SH8) ---
  {
    id: 'runtime-dead-cta-detected',
    subsystem: 'page-gen',
    confidence: 'high',
    match: (inc) => {
      const source = String(inc.source || '');
      const summary = getSummary(inc);
      if (source !== 'runtime-qa') return false;
      return (summary.includes('dead cta') || summary.includes('no effect'))
        && (summary.includes('button') || summary.includes('click') || summary.includes('cta') || hasTag(inc, 'dead-cta'));
    },
    notes: 'Runtime QA detected a dead CTA button — click produced no URL change, DOM mutation, or network request. Button lacks onClick handler or navigation wiring.',
    next_step: 'Check page-gen.ts CTA button wiring and jsx-gen.ts matchCtaToPage logic.',
    suggested_tests: ['test: all CTA buttons in generated pages have onClick handlers', 'golden: public CTA navigation'],
    suggested_invariant: null,
  },
  {
    id: 'runtime-console-error',
    subsystem: 'page-gen',
    confidence: 'medium',
    match: (inc) => {
      const source = String(inc.source || '');
      const stage = getStage(inc);
      return (source === 'runtime-qa' || stage === 'runtime-ui')
        && hasTag(inc, 'console-error');
    },
    notes: 'Runtime QA detected console errors during browser execution. May indicate undefined references, failed API calls, or component rendering errors.',
    next_step: 'Check console error content and trace to generated component or API client.',
    suggested_tests: ['test: generated app has zero console errors on page load'],
    suggested_invariant: null,
  },
  {
    id: 'runtime-navigation-failure',
    subsystem: 'jsx-gen',
    confidence: 'medium',
    match: (inc) => {
      const source = String(inc.source || '');
      const stage = getStage(inc);
      const summary = getSummary(inc);
      return (source === 'runtime-qa' || stage === 'runtime-ui')
        && (summary.includes('navigation') || summary.includes('route'))
        && (summary.includes('fail') || summary.includes('stuck') || summary.includes('did not'));
    },
    notes: 'Runtime QA navigation step failed — expected page/element not reached. Route wiring or page rendering may be broken.',
    next_step: 'Check jsx-gen.ts page routing and layout-gen.ts navigation component generation.',
    suggested_tests: ['test: all navigation routes reach expected pages'],
    suggested_invariant: null,
  },
];

// ---- Classifier ----

export function classifyIncident(incident: Record<string, unknown>): TriageResult {
  for (const pattern of PATTERN_REGISTRY) {
    if (pattern.match(incident)) {
      return {
        classification: pattern.id,
        suspected_subsystem: pattern.subsystem,
        confidence: pattern.confidence,
        triage_notes: pattern.notes,
        recommended_next_step: pattern.next_step,
        suggested_tests: pattern.suggested_tests,
        suggested_invariant: pattern.suggested_invariant,
      };
    }
  }

  // Fallback: unknown
  return {
    classification: 'unknown',
    suspected_subsystem: 'unknown',
    confidence: 'low',
    triage_notes: 'No known pattern matched. Manual investigation required.',
    recommended_next_step: 'Review incident details manually and determine subsystem.',
    suggested_tests: [],
    suggested_invariant: null,
  };
}

export function applyTriage(incidentPath: string): { incident: Record<string, unknown>; triage: TriageResult } {
  const raw = readFileSync(incidentPath, 'utf-8');
  const incident = JSON.parse(raw) as Record<string, unknown>;
  const triage = classifyIncident(incident);

  // Update incident in-place
  incident.classification = triage.classification;
  incident.suspected_subsystem = triage.suspected_subsystem;
  incident.status = 'triaged';
  incident.triage = triage;

  // Validate updated incident
  const schemaPath = join(__dirname, '..', 'docs', 'self-heal-incident.schema.json');
  const schema = JSON.parse(readFileSync(schemaPath, 'utf-8'));
  const errors = validateJsonSchema(incident, schema, schema);
  if (errors.length > 0) {
    throw new Error(`Triage produced invalid incident: ${errors.join('; ')}`);
  }

  // Write back
  writeFileSync(incidentPath, JSON.stringify(incident, null, 2));

  return { incident, triage };
}

// ---- CLI Main ----

function main(): void {
  const incidentPath = process.argv[2];
  if (!incidentPath) {
    console.error('Usage: classify-incident.ts <incident-json-path>');
    process.exit(1);
  }

  try {
    const { incident, triage } = applyTriage(incidentPath);

    console.log(`\n  Self-Heal Incident Classified\n`);
    console.log(`  ID:             ${incident.incident_id}`);
    console.log(`  Classification: ${triage.classification}`);
    console.log(`  Subsystem:      ${triage.suspected_subsystem}`);
    console.log(`  Confidence:     ${triage.confidence}`);
    console.log(`  Notes:          ${triage.triage_notes.slice(0, 100)}...`);
    console.log(`  Next step:      ${triage.recommended_next_step}`);
    if (triage.suggested_invariant) {
      console.log(`  Invariant:      ${triage.suggested_invariant}`);
    }
    console.log(`  Updated:        ${incidentPath}\n`);
  } catch (err: any) {
    console.error(`Error: ${err.message}`);
    process.exit(1);
  }
}

if (process.argv[1]?.includes('classify-incident')) {
  main();
}
