/**
 * React code generator — thin orchestrator shell.
 *
 * Re-exports generateApp, generateLayout, generatePageComponents.
 */

import type { TranspileContext } from '../context.js';
import type { UIAnalysis } from '../normalize-ui.js';
import { capitalize, indent } from './helpers.js';
import { generateStateDecls } from './state-gen.js';
import { generatePersistLoad, generatePersistSave } from './persist-gen.js';
import { generateMutations } from './mutation-gen.js';
import { generateHookEffects } from './hook-gen.js';
import { generateRootJSX } from './jsx-gen.js';

// Re-exports
export { generateLayout } from './layout-gen.js';
export { generatePageComponents } from './page-gen.js';

// ---- Main entry ----

export function generateApp(ctx: TranspileContext, analysis: UIAnalysis): string {
  const lines: string[] = [];

  lines.push("import { useState, useEffect } from 'react';");
  if (ctx.hasBackend && ctx.apiRoutes.length > 0) {
    lines.push("import * as api from './api.js';");
  }
  // Import page components for fullstack apps with pages
  if (ctx.hasBackend && analysis.hasPages) {
    for (const page of analysis.pages) {
      const pageName = capitalize(page.name);
      lines.push(`import ${pageName}Page from './pages/${pageName}Page.js';`);
    }
  }
  lines.push('');
  lines.push(`// Generated by AirEngine from ${ctx.appName}.air`);
  lines.push('export default function App() {');

  // State declarations
  lines.push(...indent(generateStateDecls(ctx), 2));
  lines.push('');

  // Page navigation state (if pages exist)
  if (analysis.hasPages) {
    const defaultPage = analysis.pages[0]?.name ?? 'home';
    lines.push(`  const [currentPage, setCurrentPage] = useState('${defaultPage}');`);
    lines.push('');
  }

  // Persist: load on mount
  const loadCode = generatePersistLoad(ctx);
  if (loadCode.length) {
    lines.push(...indent(loadCode, 2));
    lines.push('');
  }

  // Persist: save on change
  const saveCode = generatePersistSave(ctx);
  if (saveCode.length) {
    lines.push(...indent(saveCode, 2));
    lines.push('');
  }

  // Mutation functions
  const mutCode = generateMutations(ctx, analysis);
  if (mutCode.length) {
    lines.push(...indent(mutCode, 2));
    lines.push('');
  }

  // Hook effects
  const hookCode = generateHookEffects(ctx);
  if (hookCode.length) {
    lines.push(...indent(hookCode, 2));
    lines.push('');
  }

  // JSX return
  lines.push('  return (');
  lines.push(...indent(generateRootJSX(ctx, analysis), 4));
  lines.push('  );');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
