import { useState, useEffect } from 'react';

// Generated by AirEngine from projectflow.air
export default function App() {
  const [user, setUser] = useState(null);
  const [workspace, setWorkspace] = useState(null);
  const [projects, setProjects] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [comments, setComments] = useState([]);
  const [members, setMembers] = useState([]);
  const [stats, setStats] = useState({ totalTasks: 0, completed: 0, inProgress: 0, overdue: 0 });
  const [filter, setFilter] = useState("all");
  const [taskFilter, setTaskFilter] = useState("all");
  const [search, setSearch] = useState('');
  const [selectedTask, setSelectedTask] = useState(null);
  const [showModal, setShowModal] = useState(false);

  const [currentPage, setCurrentPage] = useState('login');

  // WARNING: httpOnly cookies require server-side handling
  useEffect(() => {
    try {
      const cookies = Object.fromEntries(document.cookie.split("; ").map(c => c.split("=")));
      if (cookies['projectflow-user']) { const _saved_user = JSON.parse(decodeURIComponent(cookies['projectflow-user'])); setUser(_saved_user); }
      if (cookies['projectflow-workspace']) { const _saved_workspace = JSON.parse(decodeURIComponent(cookies['projectflow-workspace'])); setWorkspace(_saved_workspace); }
    } catch (e) { /* ignore */ }
  }, []);

  useEffect(() => {
    document.cookie = 'projectflow-user=' + encodeURIComponent(JSON.stringify(user)) + '; path=/; max-age=604800';
  }, [user]);
  useEffect(() => {
    document.cookie = 'projectflow-workspace=' + encodeURIComponent(JSON.stringify(workspace)) + '; path=/; max-age=604800';
  }, [workspace]);

  const login = async (e) => {
    e?.preventDefault?.();
    setLoading(true);
    setError(null);
    try {
      // TODO: Replace with actual API call
      console.log('Login attempted');
      setUser({ name: 'User', email: 'user@example.com', token: 'mock-token' });
      setCurrentPage('dashboard');
    } catch (err) {
      setError(err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  const register = (...args) => {
    console.log('register', ...args);
  };

  const archive = (...args) => {
    console.log('archive', ...args);
  };

  const del = (id) => {
    setProjects(prev => prev.filter(item => item.id !== id));
  };

  const done = (...args) => {
    console.log('done', ...args);
  };

  const updateProfile = (...args) => {
    console.log('updateProfile', ...args);
  };

  const updateWorkspace = (...args) => {
    console.log('updateWorkspace', ...args);
  };

  const remove = (id) => {
    setProjects(prev => prev.filter(item => item.id !== id));
  };


  useEffect(() => {
    console.log('~api.stats'); // TODO: ~api.stats
    console.log('~api.projects'); // TODO: ~api.projects
  }, []);

  useEffect(() => {
    console.log('~api.projects', filter); // TODO: ~api.projects
  }, [filter]);

  useEffect(() => {
    console.log('~api.tasks', taskFilter); // TODO: ~api.tasks
  }, [taskFilter]);


  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
      <div className="max-w-[1400px] mx-auto">
        {currentPage === 'login' && (
          <div>
            <main className="flex-1 p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                  <h1 className="text-3xl font-bold">ProjectFlow</h1>
                  <p>Manage projects at the speed of thought</p>
                  <form className="space-y-4">
                    <input type="email" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={user.email} onChange={(e) => ((v) => setUser(prev => ({ ...prev, email: v })))(e.target.value)} placeholder="Email..." />
                    <input type="password" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={user.password} onChange={(e) => ((v) => setUser(prev => ({ ...prev, password: v })))(e.target.value)} placeholder="Password..." />
                    <button onClick={() => login()}>login</button>
                    <p>No account? </p>
                    <button onClick={() => register()}>register</button>
                  </form>
                </div>
              </div>
            </main>
          </div>
        )}
        {currentPage === 'dashboard' && (
          <div>
            <aside className="w-64 border-r border-[var(--border)] p-4 flex flex-col gap-4">
              <div className="text-xl font-bold">PF</div>
              <nav className="flex flex-col gap-2">
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Dashboard</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Projects</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Tasks</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Settings</button>
              </nav>
              <footer className="p-4 text-center text-sm text-[var(--muted)]">
                <span className="">muted</span>
                {workspace.plan}
              </footer>
            </aside>
            <main className="flex-1 p-6">
              <header className="flex items-center justify-between p-4 border-b border-[var(--border)]">
                <h1 className="text-3xl font-bold"></h1>
                {"Dashboard"}
              </header>
              <input type="search" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Input..." />
              <div className="grid grid-cols-4 gap-4">
                <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                  <div className="text-sm text-[var(--muted)]">Total Tasks</div>
                  <div className="text-2xl font-bold">{stats.totalTasks}</div>
                </div>
                <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                  <div className="text-sm text-[var(--muted)]">Completed</div>
                  <div className="text-2xl font-bold">{stats.completed}</div>
                </div>
                <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                  <div className="text-sm text-[var(--muted)]">In Progress</div>
                  <div className="text-2xl font-bold">{stats.inProgress}</div>
                </div>
                <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                  <div className="text-sm text-[var(--muted)]">Overdue</div>
                  <div className="text-2xl font-bold">{stats.overdue}</div>
                </div>
              </div>
              <section id="recent" className="py-16 px-6">
                <h2 className="text-2xl font-semibold">Recent Tasks</h2>
                <table className="w-full">
                  {tasks.map((task) => (
                    <div key={task.id} className="flex gap-2 items-center">
                    <span>{task.title}</span>
                    <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{task.status}</span>
                    <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{task.priority}</span>
                    <span>{task.assignee}</span>
                    <span>{task.dueDate}</span>
                    </div>
                  ))}
                </table>
              </section>
              <section id="activity" className="py-16 px-6">
                <h2 className="text-2xl font-semibold">Activity Feed</h2>
                <ul className="space-y-2">
                  {comments.map((comment) => (
                    <div key={comment.id} className="flex gap-2 items-center">
                    <span>{comment.author}</span>
                    <span>{comment.body}</span>
                    <span>{comment.created}</span>
                    </div>
                  ))}
                </ul>
              </section>
            </main>
          </div>
        )}
        {currentPage === 'projects' && (
          <div>
            <aside className="w-64 border-r border-[var(--border)] p-4 flex flex-col gap-4">
              <div className="text-xl font-bold">PF</div>
              <nav className="flex flex-col gap-2">
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Dashboard</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Projects</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Tasks</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Settings</button>
              </nav>
            </aside>
            <main className="flex-1 p-6">
              <header className="flex items-center justify-between p-4 border-b border-[var(--border)]">
                <h1 className="text-3xl font-bold"></h1>
                {"Projects"}
              </header>
              <div className="flex gap-2">
                {["all", "active", "archived"].map((_tab) => (
                  <button key={_tab} className={`px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors ${filter === _tab ? 'bg-[var(--accent)] text-white' : 'bg-transparent hover:bg-[var(--hover)]'}`} onClick={() => setFilter(_tab)}>{_tab}</button>
                ))}
              </div>
              <button className="bg-[var(--accent)] text-white px-4 py-2 rounded-[var(--radius)] cursor-pointer hover:opacity-90 transition-colors">New Project</button>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {projects.filter(_item => filter === 'all' || _item.category === filter || _item.done === (filter === 'done')).map((project) => (
                  <div key={project.id} className="flex gap-2 items-center">
                  <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                    <h2 className="text-2xl font-semibold">{project.name}</h2>
                    <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{project.status}</span>
                    <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                      <div className="text-sm text-[var(--muted)]">Tasks</div>
                      <div className="text-2xl font-bold">{project.taskCount}</div>
                    </div>
                    <div className="flex gap-4 items-center">
                      <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Open</button>
                      <button onClick={() => archive(project.id)}>archive</button>
                    </div>
                  </div>
                  </div>
                ))}
              </div>
            </main>
          </div>
        )}
        {currentPage === 'tasks' && (
          <div>
            <aside className="w-64 border-r border-[var(--border)] p-4 flex flex-col gap-4">
              <div className="text-xl font-bold">PF</div>
              <nav className="flex flex-col gap-2">
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Dashboard</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Projects</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Tasks</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Settings</button>
              </nav>
            </aside>
            <main className="flex-1 p-6">
              <header className="flex items-center justify-between p-4 border-b border-[var(--border)]">
                <h1 className="text-3xl font-bold"></h1>
                {"Tasks"}
              </header>
              <div className="flex gap-2">
                {["all", "todo", "in_progress", "review", "done"].map((_tab) => (
                  <button key={_tab} className={`px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors ${taskFilter === _tab ? 'bg-[var(--accent)] text-white' : 'bg-transparent hover:bg-[var(--hover)]'}`} onClick={() => setTaskFilter(_tab)}>{_tab}</button>
                ))}
              </div>
              <button className="bg-[var(--accent)] text-white px-4 py-2 rounded-[var(--radius)] cursor-pointer hover:opacity-90 transition-colors">New Task</button>
              <div className="grid grid-cols-4 gap-4">
                <section id="todo" className="py-16 px-6">
                  <h2 className="text-2xl font-semibold">To Do</h2>
                  <ul className="space-y-2">
                    {tasks.map((task) => (
                      <div key={task.id} className="flex gap-2 items-center">
                      <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                        <span>{task.title}</span>
                        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{task.priority}</span>
                        <button className="p-2 rounded-full hover:bg-[var(--hover)] cursor-pointer transition-colors" onClick={() => del(task.id)}>✕</button>
                      </div>
                      </div>
                    ))}
                  </ul>
                </section>
                <section id="progress" className="py-16 px-6">
                  <h2 className="text-2xl font-semibold">In Progress</h2>
                  <ul className="space-y-2">
                    {tasks.map((task) => (
                      <div key={task.id} className="flex gap-2 items-center">
                      <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                        <span>{task.title}</span>
                        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{task.priority}</span>
                        <span>{task.assignee}</span>
                      </div>
                      </div>
                    ))}
                  </ul>
                </section>
                <section id="review" className="py-16 px-6">
                  <h2 className="text-2xl font-semibold">Review</h2>
                  <ul className="space-y-2">
                    {tasks.map((task) => (
                      <div key={task.id} className="flex gap-2 items-center">
                      <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                        <span>{task.title}</span>
                        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{task.priority}</span>
                        <button onClick={() => done(task.id)}>done</button>
                      </div>
                      </div>
                    ))}
                  </ul>
                </section>
                <section id="done" className="py-16 px-6">
                  <h2 className="text-2xl font-semibold">Done</h2>
                  <ul className="space-y-2">
                    {tasks.map((task) => (
                      <div key={task.id} className="flex gap-2 items-center">
                      <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                        <span>{task.title}</span>
                        <span>{task.assignee}</span>
                      </div>
                      </div>
                    ))}
                  </ul>
                </section>
              </div>
            </main>
          </div>
        )}
        {currentPage === 'settings' && (
          <div>
            <aside className="w-64 border-r border-[var(--border)] p-4 flex flex-col gap-4">
              <div className="text-xl font-bold">PF</div>
              <nav className="flex flex-col gap-2">
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Dashboard</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Projects</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Tasks</button>
                <button className="bg-transparent hover:bg-[var(--hover)] px-4 py-2 rounded-[var(--radius)] cursor-pointer transition-colors">Settings</button>
              </nav>
            </aside>
            <main className="flex-1 p-6">
              <header className="flex items-center justify-between p-4 border-b border-[var(--border)]">
                <h1 className="text-3xl font-bold"></h1>
                {"Settings"}
              </header>
              <div className="grid grid-cols-2 gap-4">
                <section id="profile" className="py-16 px-6">
                  <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                    <h2 className="text-2xl font-semibold">Profile</h2>
                    <form className="space-y-4">
                      <input type="text" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={user.name} onChange={(e) => ((v) => setUser(prev => ({ ...prev, name: v })))(e.target.value)} placeholder="Text..." />
                      <input type="email" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={user.email} onChange={(e) => ((v) => setUser(prev => ({ ...prev, email: v })))(e.target.value)} placeholder="Email..." />
                      <button onClick={() => updateProfile()}>updateProfile</button>
                    </form>
                  </div>
                </section>
                <section id="workspace" className="py-16 px-6">
                  <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                    <h2 className="text-2xl font-semibold">Workspace</h2>
                    <form className="space-y-4">
                      <input type="text" className="w-full border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none focus:border-[var(--accent)]" value={workspace.name} onChange={(e) => ((v) => setWorkspace(prev => ({ ...prev, name: v })))(e.target.value)} placeholder="Text..." />
                      <select className="border border-[var(--border-input)] rounded-[var(--radius)] px-3 py-2 bg-transparent focus:outline-none" value={workspace.plan} onChange={(e) => ((v) => setWorkspace(prev => ({ ...prev, plan: v })))(e.target.value)}>

                      </select>
                      <button onClick={() => updateWorkspace()}>updateWorkspace</button>
                    </form>
                  </div>
                </section>
                <section id="team" className="py-16 px-6">
                  <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                    <h2 className="text-2xl font-semibold">Team Members</h2>
                    <button className="bg-[var(--accent)] text-white px-4 py-2 rounded-[var(--radius)] cursor-pointer hover:opacity-90 transition-colors">Invite Member</button>
                    <table className="w-full">
                      {members.map((member) => (
                        <div key={member.id} className="flex gap-2 items-center">
                        <span>{member.name}</span>
                        <span>{member.email}</span>
                        <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-[var(--accent)]/20 text-[var(--accent)]">{member.role}</span>
                        <button className="p-2 rounded-full hover:bg-[var(--hover)] cursor-pointer transition-colors" onClick={() => remove(member.id)}>✕</button>
                        </div>
                      ))}
                    </table>
                  </div>
                </section>
                <section id="billing" className="py-16 px-6">
                  <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 shadow-sm">
                    <h2 className="text-2xl font-semibold">Billing</h2>
                    <div className="rounded-[var(--radius)] border border-[var(--border)] p-4 text-center">
                      <div className="text-sm text-[var(--muted)]">Current Plan</div>
                      <div className="text-2xl font-bold">{workspace.plan}</div>
                    </div>
                    <button className="bg-[var(--accent)] text-white px-4 py-2 rounded-[var(--radius)] cursor-pointer hover:opacity-90 transition-colors">Upgrade</button>
                  </div>
                </section>
              </div>
            </main>
          </div>
        )}
      </div>
    </div>
  );
}
