/**
 * README Generator
 *
 * Generates a README.md for the fullstack project with setup instructions,
 * API route tables, and database model documentation.
 */

import type { TranspileContext } from '../context.js';
import type { AirType } from '../../parser/types.js';
import { expandCrud } from '../route-utils.js';

export function generateReadme(ctx: TranspileContext): string {
  const lines: string[] = [];

  lines.push(`# ${capitalize(ctx.appName)}`);
  lines.push('');
  lines.push(`Full-stack application generated by AirEngine from \`${ctx.appName}.air\`.`);
  lines.push('');

  // Setup
  lines.push('## Setup');
  lines.push('');
  lines.push('### Client');
  lines.push('```bash');
  lines.push('cd client');
  lines.push('npm install');
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');
  lines.push('### Server');
  lines.push('```bash');
  lines.push('cd server');
  lines.push('npm install');
  if (ctx.db) {
    lines.push('npx prisma db push');
    lines.push('npx tsx seed.ts');
  }
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');

  // API routes table
  if (ctx.apiRoutes.length > 0) {
    const routes = expandCrud(ctx.apiRoutes);
    lines.push('## API Routes');
    lines.push('');
    lines.push('| Method | Path | Handler |');
    lines.push('|--------|------|---------|');
    for (const route of routes) {
      lines.push(`| ${route.method} | ${route.path} | \`${route.handler}\` |`);
    }
    lines.push('');
  }

  // Database models table
  if (ctx.db) {
    lines.push('## Database Models');
    lines.push('');
    for (const model of ctx.db.models) {
      lines.push(`### ${model.name}`);
      lines.push('');
      lines.push('| Field | Type | Constraints |');
      lines.push('|-------|------|-------------|');
      for (const field of model.fields) {
        const constraints: string[] = [];
        if (field.primary) constraints.push('primary');
        if (field.required) constraints.push('required');
        if (field.auto) constraints.push('auto');
        if (field.default !== undefined) constraints.push(`default: ${field.default}`);
        lines.push(`| ${field.name} | ${describeType(field.type)} | ${constraints.join(', ') || '-'} |`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('Generated by [AirEngine](https://github.com/AirEngine/AirEngine)');
  lines.push('');

  return lines.join('\n');
}

export function describeType(type: AirType): string {
  switch (type.kind) {
    case 'optional': return `${describeType((type as { kind: 'optional'; of: AirType }).of)}?`;
    case 'enum': return `enum(${(type as { kind: 'enum'; values: string[] }).values.join(', ')})`;
    case 'array': return `${describeType((type as { kind: 'array'; of: AirType }).of)}[]`;
    default: return type.kind;
  }
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}
