/**
 * README Generator
 *
 * Generates a README.md for the fullstack project with setup instructions,
 * API route tables, and database model documentation.
 */

import type { TranspileContext } from '../context.js';
import type { AirType } from '../../parser/types.js';

export function generateReadme(ctx: TranspileContext): string {
  const lines: string[] = [];

  lines.push(`# ${capitalize(ctx.appName)}`);
  lines.push('');
  lines.push(`Full-stack application generated by AirEngine from \`${ctx.appName}.air\`.`);
  lines.push('');

  // Setup
  lines.push('## Setup');
  lines.push('');
  lines.push('### Client');
  lines.push('```bash');
  lines.push('cd client');
  lines.push('npm install');
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');
  lines.push('### Server');
  lines.push('```bash');
  lines.push('cd server');
  lines.push('npm install');
  if (ctx.db) {
    lines.push('npx prisma db push');
    lines.push('npx tsx seed.ts');
  }
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');

  // API routes table
  if (ctx.apiRoutes.length > 0) {
    const routes = ctx.expandedRoutes;
    lines.push('## API Routes');
    lines.push('');
    lines.push('| Method | Path | Handler |');
    lines.push('|--------|------|---------|');
    for (const route of routes) {
      lines.push(`| ${route.method} | ${route.path} | \`${route.handler}\` |`);
    }
    lines.push('');
  }

  // Database models table
  if (ctx.db) {
    lines.push('## Database Models');
    lines.push('');
    for (const model of ctx.db.models) {
      lines.push(`### ${model.name}`);
      lines.push('');
      lines.push('| Field | Type | Constraints |');
      lines.push('|-------|------|-------------|');
      for (const field of model.fields) {
        const constraints: string[] = [];
        if (field.primary) constraints.push('primary');
        if (field.required) constraints.push('required');
        if (field.auto) constraints.push('auto');
        if (field.default !== undefined) constraints.push(`default: ${field.default}`);
        lines.push(`| ${field.name} | ${describeType(field.type)} | ${constraints.join(', ') || '-'} |`);
      }
      lines.push('');
    }
  }

  // Deployment section (only if @deploy exists)
  if (ctx.deploy) {
    const target = String(ctx.deploy.properties.target ?? 'docker');
    const port = resolvePort(ctx);

    if (target === 'docker') {
      lines.push('## Deployment');
      lines.push('');
      lines.push('### Docker Compose');
      lines.push('```bash');
      lines.push('cp server/.env.example server/.env');
      lines.push('# Edit server/.env with production values');
      lines.push('docker compose up --build -d');
      lines.push('```');
      lines.push('');
      if (ctx.db) {
        lines.push('### Database Initialization (before first deploy)');
        lines.push('```bash');
        lines.push('cd server');
        lines.push('mkdir -p data');
        lines.push('DATABASE_URL="file:../data/app.db" npx prisma db push');
        lines.push('DATABASE_URL="file:../data/app.db" npx tsx seed.ts  # optional');
        lines.push('```');
        lines.push('');
        lines.push('> These commands write to `server/data/app.db` on the host, which Docker Compose bind-mounts into the container at `/app/data/app.db`.');
        lines.push('');
      }
      lines.push('### Manual Docker Build');
      lines.push('```bash');
      lines.push('cd server');
      lines.push(`docker build -t ${ctx.appName}-server .`);
      lines.push(`docker run -p ${port}:${port} --env-file .env ${ctx.appName}-server`);
      lines.push('```');
      lines.push('');
    } else {
      lines.push('## Deployment');
      lines.push('');
      lines.push(`> TODO: Deploy target \`${target}\` is not yet supported by AirEngine. Only \`docker\` is currently implemented.`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('Generated by [AirEngine](https://github.com/AirEngine/AirEngine)');
  lines.push('');

  return lines.join('\n');
}

export function describeType(type: AirType): string {
  switch (type.kind) {
    case 'optional': return `${describeType((type as { kind: 'optional'; of: AirType }).of)}?`;
    case 'enum': return `enum(${(type as { kind: 'enum'; values: string[] }).values.join(', ')})`;
    case 'array': return `${describeType((type as { kind: 'array'; of: AirType }).of)}[]`;
    default: return type.kind;
  }
}

function resolvePort(ctx: TranspileContext): string {
  if (ctx.deploy?.properties.port !== undefined) {
    return String(ctx.deploy.properties.port);
  }
  if (ctx.env) {
    const portVar = ctx.env.vars.find(v => v.name === 'PORT');
    if (portVar?.default !== undefined) return String(portVar.default);
  }
  return '3001';
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}
